# Generated by Django 5.1.4 on 2024-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_managers_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('eulogi', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
