# Generated by Django 5.1.4 on 2024-12-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
