# Generated by Django 5.1.4 on 2024-12-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_list_listtemplate_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtemplate',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
